"""
Bootstrap: calls the ai-engineering-team microservice to generate
the feature-to-pr project, then saves all artifacts to disk.
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path

import httpx

HOST = "http://localhost:8000"
FEATURE_REQUEST = """
Build a pipeline service in Python that accepts a GitHub repository URL and a
feature description, clones the repo, analyzes the existing codebase structure,
and generates a ready-to-merge pull request with implementation code, tests,
and a PR description. The service should expose a REST API endpoint, handle
errors gracefully, and clean up temporary files after the PR is created.
"""

PERSONA_ORDER = ["architect", "developer", "security", "qa", "tech_lead"]
ARTIFACT_MAP = {
    "architect": "architecture.md",
    "developer": "implementation.py",
    "security":  "security_report.md",
    "qa":        "test_suite.py",
    "tech_lead": "review.md",
}


def extract_code(text: str) -> str:
    """Extract first fenced Python code block, or return full text."""
    blocks = re.findall(r"```(?:python|pytest)?\n(.*?)```", text, re.DOTALL)
    return "\n\n".join(blocks) if blocks else text


def save_artifacts(results: dict[str, str]) -> Path:
    out = Path(".")

    # Save individual artifact files
    for persona, response in results.items():
        filename = ARTIFACT_MAP[persona]
        content = extract_code(response) if filename.endswith(".py") else response
        (out / filename).write_text(content, encoding="utf-8")
        print(f"  ✅ saved {filename}")

    # Save full demo log capturing every persona's raw output
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log = f"# AI Engineering Team — Demo Log\n\n"
    log += f"**Feature Request:** {FEATURE_REQUEST.strip()}\n\n"
    log += f"**Generated:** {generated_at}\n\n"
    log += "---\n\n"

    for persona in PERSONA_ORDER:
        if persona not in results:
            continue
        filename = ARTIFACT_MAP[persona]
        emoji = {"architect": "🏗️", "developer": "💻", "security": "🔒",
                 "qa": "🧪", "tech_lead": "⭐"}[persona]
        name = {"architect": "Architect", "developer": "Developer",
                "security": "Security Reviewer", "qa": "QA Engineer",
                "tech_lead": "Tech Lead"}[persona]
        log += f"## {emoji} {name}\n\n"
        log += f"> Output saved to `{filename}`\n\n"
        log += results[persona]
        log += "\n\n---\n\n"

    (out / "demo_log.md").write_text(log, encoding="utf-8")
    print(f"  ✅ saved demo_log.md")

    return out


def main():
    results: dict[str, str] = {}
    current_persona = None

    print("\n🚀 Calling ai-engineering-team microservice...\n")

    with httpx.Client(timeout=300) as client:
        with client.stream(
            "POST",
            f"{HOST}/review/stream",
            json={"feature_request": FEATURE_REQUEST.strip()},
            headers={"Accept": "text/event-stream"},
        ) as resp:
            resp.raise_for_status()

            for line in resp.iter_lines():
                if not line.startswith("data:"):
                    continue
                payload = json.loads(line[5:].strip())

                if payload.get("done"):
                    print("\n\n✅ All personas complete.\n")
                    break

                persona = payload["persona"]
                delta = payload["delta"]

                if persona != current_persona:
                    current_persona = persona
                    results[persona] = ""
                    print(f"\n{'='*60}")
                    print(f"  {payload['emoji']}  {payload['name']}")
                    print(f"{'='*60}\n")

                results[persona] += delta
                print(delta, end="", flush=True)

    print("\n📁 Saving artifacts...\n")
    save_artifacts(results)
    print("\n🎉 feature-to-pr project generated by AI Engineering Team!\n")


if __name__ == "__main__":
    main()
