"""
Extracts code blocks and content from persona markdown responses.
Each persona's output is saved as a specific artifact type.
"""

import re


def extract_code_blocks(text: str, language: str = "") -> list[str]:
    """Pull fenced code blocks from markdown, optionally filtered by language."""
    pattern = rf"```{language}.*?\n(.*?)```" if language else r"```(?:\w+)?\n?(.*?)```"
    return re.findall(pattern, text, re.DOTALL)


def persona_to_artifact(persona_key: str, response: str) -> tuple[str, str]:
    """
    Convert a persona response to (filename, content).
    Developer and QA responses have code extracted; others are saved as-is.
    """
    if persona_key == "architect":
        return "architecture.md", f"# Architecture Design\n\n{response}"

    elif persona_key == "developer":
        blocks = extract_code_blocks(response, "python") or extract_code_blocks(response)
        if blocks:
            header = "# Implementation\n\n"
            header += "# Generated by AI Developer persona\n"
            header += "# Review before using in production\n\n"
            content = header + "\n\n".join(blocks)
        else:
            content = f"# Implementation\n\n{response}"
        return "implementation.py", content

    elif persona_key == "security":
        return "security_report.md", f"# Security Review\n\n{response}"

    elif persona_key == "qa":
        blocks = (
            extract_code_blocks(response, "python")
            or extract_code_blocks(response, "pytest")
            or extract_code_blocks(response)
        )
        if blocks:
            header = "# Test Suite\n\n"
            header += "# Generated by AI QA Engineer persona\n"
            header += "# Run with: pytest test_suite.py\n\n"
            content = header + "\n\n".join(blocks)
        else:
            content = f"# Test Suite\n\n{response}"
        return "test_suite.py", content

    elif persona_key == "tech_lead":
        return "review.md", f"# Tech Lead Review\n\n{response}"

    return f"{persona_key}.md", response
