import time
from pathlib import Path

import git
from github import Github, GithubException


def create_pr(
    repo_path: Path,
    repo_url: str,
    github_token: str,
    generated: dict,
    base_branch: str = "main",
) -> str:
    """
    1. Write generated files into the cloned repo.
    2. Create a new branch, commit, push.
    3. Open a PR via PyGitHub.
    Returns the PR URL.
    """
    # --- Write files ---
    files_to_create = generated.get("files_to_create", {})
    files_to_modify = generated.get("files_to_modify", {})
    pr_title = generated.get("pr_title", "AI-generated feature implementation")
    pr_body = generated.get("pr_body", "Implemented by feature-to-pr service.")

    for rel_path, content in {**files_to_create, **files_to_modify}.items():
        target = repo_path / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    # --- Git operations ---
    repo = git.Repo(str(repo_path))

    # Unshallow so our branch shares history with the remote base branch
    try:
        repo.git.fetch("--unshallow")
    except git.GitCommandError:
        pass  # already a full clone, ignore

    branch_name = f"feature/ai-impl-{int(time.time())}"
    repo.git.checkout("-b", branch_name)
    repo.git.add(".")
    repo.index.commit(f"{pr_title}\n\nGenerated by feature-to-pr service.")

    # Set remote with token for auth
    origin = repo.remote("origin")
    authenticated_url = _inject_token(repo_url, github_token)
    origin.set_url(authenticated_url)

    # Disable macOS credential helper so the token in the URL is used directly
    repo.config_writer().set_value("credential", "helper", "").release()
    with repo.git.custom_environment(GIT_TERMINAL_PROMPT="0"):
        origin.push(branch_name)

    # --- Open PR ---
    gh = Github(github_token)
    repo_name = _parse_repo_name(repo_url)
    gh_repo = gh.get_repo(repo_name)

    pr = gh_repo.create_pull(
        title=pr_title,
        body=pr_body,
        head=branch_name,
        base=base_branch,
    )
    return pr.html_url


def _inject_token(repo_url: str, token: str) -> str:
    """Convert https://github.com/... → https://<token>@github.com/..."""
    return repo_url.replace("https://", f"https://{token}@", 1)


def _parse_repo_name(repo_url: str) -> str:
    """Extract 'owner/repo' from a GitHub URL."""
    # Handle trailing .git
    url = repo_url.rstrip("/")
    if url.endswith(".git"):
        url = url[:-4]
    # e.g. https://github.com/owner/repo → owner/repo
    parts = url.split("github.com/")
    if len(parts) != 2:
        raise ValueError(f"Cannot parse repo name from URL: {repo_url}")
    return parts[1]
